package Comparator;

public enum UniversityEnumComparator {
    UNIVERSITY_ID_COMPARATOR,
    UNIVERSITY_FULL_NAME_COMPARATOR,
    SHORT_NAME_COMPARATOR,
    YEAR_OF_FOUNDATION_COMPARATOR,
    STUDY_PROFILE_COMPARATOR;
}
